from __future__ import annotations

import importlib.util
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "build_canon_index.py"
SPEC = importlib.util.spec_from_file_location("nero_build_canon_index_test", SCRIPT)
assert SPEC and SPEC.loader
M = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(M)


def write(root: Path, rel: str, text: str) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def git(root: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


class BuildCanonIndexTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        git(self.root, "init", "--quiet")
        write(self.root, ".gitignore", ".pytest_cache/\n")
        write(self.root, "docs/tracked.md", "# Tracked\n")
        git(self.root, "add", ".gitignore", "docs/tracked.md")

    def tearDown(self):
        self._tmp.cleanup()

    def paths(self) -> list[str]:
        return [
            path.relative_to(self.root).as_posix()
            for path in M.markdown_paths(self.root)
        ]

    def test_ignored_cache_markdown_does_not_enter_inventory(self):
        write(self.root, "docs/draft.md", "# Draft\n")
        write(self.root, ".pytest_cache/README.md", "# Generated by pytest\n")

        self.assertEqual(self.paths(), ["docs/draft.md", "docs/tracked.md"])

    def test_structural_filter_rejects_force_tracked_cache(self):
        write(self.root, ".pytest_cache/README.md", "# Generated by pytest\n")
        git(self.root, "add", "--force", ".pytest_cache/README.md")

        self.assertNotIn(".pytest_cache/README.md", self.paths())

    def test_ignored_cache_does_not_change_rendered_index(self):
        before = M.render(M.collect(self.root, self.root / "docs/canon/INDEX.md"))
        write(self.root, ".pytest_cache/README.md", "# Generated by pytest\n")
        after = M.render(M.collect(self.root, self.root / "docs/canon/INDEX.md"))

        self.assertEqual(after, before)


if __name__ == "__main__":
    unittest.main()
