#!/usr/bin/env python3
"""Regenerate docs/canon/INDEX.md - the master knowledge index.

Deterministic, standard-library only (Constitution section 3: don't reason
when you can know). Walks every knowledge markdown file, reads YAML
frontmatter when present, infers sane defaults when not (flagging the file
`unmigrated`), and rewrites docs/canon/INDEX.md. Never edit INDEX.md by hand.

Usage:  python scripts/build_canon_index.py [--check]
        --check: exit 1 if INDEX.md would change (drift detector for verify).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX = REPO / "docs" / "canon" / "INDEX.md"

EXCLUDE_DIRS = {
    ".git", ".venv", "venv", "node_modules", "__pycache__",
    "data", "models", "output", "_nero_preview",
}

# (path-prefix, layer, owner) inference for files without frontmatter.
INFERENCE = [
    ("School/", "operational", "school"),
    ("docs/adr/", "core", "shared"),
    ("docs/archive/", "archival", "shared"),
    ("docs/reviews/", "operational", "shared"),
    (".claude/", "operational", "claude-lane"),
    (".codex/", "operational", "codex-lane"),
    ("skills/", "operational", "shared"),
]

CORE_NAMES = {"docs/CONSTITUTION.md", "docs/VISION.md", "docs/DIRECTIVE.md"}


def parse_frontmatter(text: str) -> dict:
    """Minimal flat YAML frontmatter reader (scalars only; lists ignored)."""
    meta = {}
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return meta
    for line in lines[1:80]:
        s = line.strip()
        if s == "---":
            break
        if ":" in line and not line.startswith(" ") and not s.startswith("-"):
            key, _, val = line.partition(":")
            val = val.strip().strip("'\"")
            if val and not val.startswith("["):
                meta[key.strip()] = val
    return meta


def first_heading(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def classify(rel: str, meta: dict):
    if "layer" in meta:
        return meta["layer"], meta.get("owner", "shared"), False
    for prefix, layer, owner in INFERENCE:
        if rel.startswith(prefix):
            return layer, owner, True
    if rel in CORE_NAMES:
        return "core", "toni", True
    return "operational", "shared", True


def collect() -> list:
    rows = []
    for path in sorted(REPO.rglob("*.md")):
        if path == INDEX:  # the index never indexes itself
            continue
        rel_parts = path.relative_to(REPO).parts
        if any(p in EXCLUDE_DIRS for p in rel_parts):
            continue
        rel = "/".join(rel_parts)
        try:
            # utf-8-sig consumes an optional BOM while remaining identical to
            # utf-8 for ordinary files, so valid frontmatter is never hidden.
            text = path.read_text(encoding="utf-8-sig", errors="replace")
        except OSError:
            continue
        meta = parse_frontmatter(text)
        layer, owner, inferred = classify(rel, meta)
        rows.append({
            "path": rel,
            "id": meta.get("id", ""),
            "title": meta.get("title") or first_heading(text) or rel,
            "layer": layer,
            "type": meta.get("type", ""),
            "status": meta.get("status", ""),
            "owner": owner,
            "flag": "unmigrated" if inferred else "",
        })
    return rows


def cluster(rel: str) -> str:
    parts = rel.split("/")
    if parts[0] == "docs" and len(parts) > 2:
        return "docs/" + parts[1]
    if parts[0] == "docs":
        return "docs (root)"
    if len(parts) == 1:
        return "(repo root)"
    return parts[0]


def render(rows: list) -> str:
    total = len(rows)
    migrated = sum(1 for r in rows if not r["flag"])
    out = [
        "<!-- GENERATED by scripts/build_canon_index.py - do not edit by hand. -->",
        "",
        "# Nero Knowledge Index",
        "",
        f"{total} knowledge files - {migrated} carrying canon frontmatter - "
        f"{total - migrated} not yet migrated (see MIGRATION_PLAN.md).",
        "",
        "Read order for a fresh model: capsule -> `docs/CONSTITUTION.md` -> "
        "`docs/canon/README.md` -> this index -> `docs/PROJECT_BRIEF.md`.",
        "",
    ]
    groups = {}
    for r in rows:
        groups.setdefault(cluster(r["path"]), []).append(r)
    for name in sorted(groups):
        out.append("## " + name)
        out.append("")
        out.append("| File | Title | Layer | Status | Owner | |")
        out.append("|---|---|---|---|---|---|")
        for r in groups[name]:
            title = r["title"][:60]
            out.append(
                "| [{p}](/{p}) | {t} | {l} | {s} | {o} | {f} |".format(
                    p=r["path"], t=title, l=r["layer"],
                    s=r["status"] or "-", o=r["owner"], f=r["flag"],
                )
            )
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    rows = collect()
    new = render(rows)
    old = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
    if "--check" in sys.argv:
        if new != old:
            print("INDEX.md is stale - run: python scripts/build_canon_index.py")
            return 1
        print("INDEX.md is current.")
        return 0
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(new, encoding="utf-8")
    print("Wrote {} - {} files indexed.".format(INDEX, len(rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
